# Site settings
title: Alberto Pérez Cano
description: Web Personal
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://www.albertopc.com"

# User settings
username: Alberto Pérez Cano
user_description: Actualmente poseo el título de técnico superior en Administración de Sistemas Informáticos en Red. Me defino como una persona curiosa, con ganas de aprender, con capacidad para trabajar en equipo y dirigir a un grupo de personas. Entre otras de mis aptitudes está el saber escuchar, el orden y el afán por desarrollar siempre mis tareas de la mejor forma posible. Son mis claves para poder desarrollar una buena labor. Soy un apasionado de las nuevas tecnologías y actualmente busco un proyecto que me permita seguir aprendiendo día a día y potenciar mi crecimiento profesional y personal.
user_title: SysAdmin
email: albertopc92@gmail.com
twitter_username: Albertopc92
github_username:  albertopc92
#gplus_username:

# Google-analytics
google-analytics:
  id: "UA-113821237-1"

exclude: ['package.json', 'src' , 'node_modules']
